name: Sync and Replace

on:
  schedule:
    - cron: '0 2 * * *' # 每天凌晨 2 点运行一次
  workflow_dispatch: # 手动触发工作流

jobs:
  sync-and-replace:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 添加上游仓库为 remote
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/c1pher-cn/iptv-hangzhou-dianxin.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories || true

      # 3. 替换 IP 地址
      - name: Replace IP address
        run: |
          find . -type f \( -name "杭州电信高清.m3u" -o -name "杭州电信高清.m3u8" \) -exec sed -i 's/192\.168\.1\.1/192.168.8.1/g' {} \;

      # 4. 提交更改
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync with upstream and replace IP address" || echo "No changes to commit"

      # 5. 推送更改到你的仓库
      - name: Push changes
        run: |
          git push origin main
